// Regenerates robots.txt and sitemap-*.xml on demand and uploads them to the
// `site-assets` storage bucket under `seo/`. Admin-only.
//
// POST /functions/v1/regenerate-seo  { host?: string }
// Returns: { robots: url, sitemapIndex: url, sitemaps: [{lang, url}] }
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const BUCKET = "site-assets";

const STATIC_ROUTES: Record<string, string[]> = {
  ca: ["/", "/cataleg", "/contacte", "/llista-naixement", "/politica-cookies"],
  es: ["/", "/cataleg", "/contacto", "/llista-naixement", "/politica-de-cookies"],
};

const PRIVATE_PATHS = [
  "/llista-naixement/",
  "/la-meva-llista",
  "/el-meu-compte",
  "/cistella",
  "/checkout",
  "/login",
  "/registre",
  "/recuperar-contrasenya",
  "/reset-password",
  "/admin",
];

function xmlEscape(s: string) {
  return s.replace(/[<>&"']/g, (c) =>
    ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;", "'": "&apos;" }[c]!),
  );
}

function buildUrlset(entries: { loc: string; lastmod?: string | null }[]) {
  const urls = entries
    .map(
      (e) =>
        `  <url>\n    <loc>${xmlEscape(e.loc)}</loc>${
          e.lastmod ? `\n    <lastmod>${String(e.lastmod).slice(0, 10)}</lastmod>` : ""
        }\n  </url>`,
    )
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`;
}

function buildSitemapIndex(items: { loc: string; lastmod: string }[]) {
  const body = items
    .map(
      (s) =>
        `  <sitemap>\n    <loc>${xmlEscape(s.loc)}</loc>\n    <lastmod>${s.lastmod}</lastmod>\n  </sitemap>`,
    )
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</sitemapindex>\n`;
}

function buildRobots(host: string, sitemapUrl: string) {
  const ua = (name: string) =>
    [`User-agent: ${name}`, "Allow: /", ...PRIVATE_PATHS.map((p) => `Disallow: ${p}`)].join("\n");
  return [
    "# El Mussolet — robots.txt",
    "# Generated by /functions/v1/regenerate-seo",
    `# Host: ${host}`,
    "",
    ua("Googlebot"),
    "",
    ua("Bingbot"),
    "",
    ua("Twitterbot"),
    "",
    ua("facebookexternalhit"),
    "",
    ua("*"),
    "",
    `Sitemap: ${sitemapUrl}`,
    "",
  ].join("\n");
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors });

  try {
    // AuthN/AuthZ: must be admin.
    const authHeader = req.headers.get("Authorization") || "";
    const userClient = createClient(SUPABASE_URL, Deno.env.get("SUPABASE_ANON_KEY")!, {
      global: { headers: { Authorization: authHeader } },
      auth: { persistSession: false },
    });
    const { data: userData } = await userClient.auth.getUser();
    if (!userData?.user) {
      return new Response(JSON.stringify({ error: "unauthorized" }), {
        status: 401,
        headers: { ...cors, "Content-Type": "application/json" },
      });
    }
    const sb = createClient(SUPABASE_URL, SERVICE_KEY, {
      auth: { autoRefreshToken: false, persistSession: false },
    });
    const { data: isAdmin } = await sb.rpc("is_admin", { _user_id: userData.user.id });
    if (!isAdmin) {
      return new Response(JSON.stringify({ error: "forbidden" }), {
        status: 403,
        headers: { ...cors, "Content-Type": "application/json" },
      });
    }

    const body = await req.json().catch(() => ({}));
    const host = String(body.host || "https://elmussolet.lovable.app").replace(/\/$/, "");

    // Selective targets. If not provided, regenerate everything (back-compat).
    const targets = (body.targets || {}) as {
      robots?: boolean;
      sitemapIndex?: boolean;
      langs?: string[] | "all";
    };
    const hasTargets = body.targets && typeof body.targets === "object";
    const doRobots = hasTargets ? !!targets.robots : true;
    const doIndex = hasTargets ? !!targets.sitemapIndex : true;
    const langFilter: string[] | "all" = hasTargets
      ? targets.langs === "all"
        ? "all"
        : Array.isArray(targets.langs)
          ? targets.langs
          : []
      : "all";

    // Languages
    const { data: langRows } = await sb
      .from("languages")
      .select("code, sort_order, is_enabled")
      .eq("is_enabled", true)
      .order("sort_order", { ascending: true });
    const langs = (langRows?.map((l: any) => l.code).filter(Boolean) as string[]) || ["ca", "es"];

    const { data: products } = await sb
      .from("products")
      .select("id, slug, updated_at, is_active")
      .eq("is_active", true);
    const { data: productTranslations } = await sb
      .from("product_translations")
      .select("product_id, language, slug");
    const { data: pages } = await sb
      .from("cms_blocks")
      .select("slug, updated_at, kind, is_active")
      .eq("kind", "page")
      .eq("is_active", true);
    const { data: categories } = await sb
      .from("categories")
      .select("id, slug, updated_at, is_active")
      .eq("is_active", true);
    const { data: categoryTranslations } = await sb
      .from("category_translations")
      .select("category_id, language, slug");

    const today = new Date().toISOString().slice(0, 10);
    const indexItems: { loc: string; lastmod: string }[] = [];
    const uploaded: { path: string; content: string; type: string }[] = [];

    const wantsLang = (code: string) =>
      langFilter === "all" ? true : (langFilter as string[]).includes(code);

    for (const lang of langs) {
      const entries: { loc: string; lastmod?: string | null }[] = [];
      for (const r of STATIC_ROUTES[lang] || STATIC_ROUTES.ca)
        entries.push({ loc: `${host}${r}` });

      const ptByProduct: Record<string, string | null> = {};
      for (const t of productTranslations || []) {
        if ((t as any).language === lang && (t as any).slug)
          ptByProduct[(t as any).product_id] = (t as any).slug;
      }
      for (const p of products || []) {
        const slug = ptByProduct[(p as any).id] || (p as any).slug;
        entries.push({ loc: `${host}/producte/${slug}`, lastmod: (p as any).updated_at });
      }
      for (const pg of pages || [])
        entries.push({ loc: `${host}/pagina/${(pg as any).slug}`, lastmod: (pg as any).updated_at });

      const ctByCategory: Record<string, string | null> = {};
      for (const t of categoryTranslations || []) {
        if ((t as any).language === lang && (t as any).slug)
          ctByCategory[(t as any).category_id] = (t as any).slug;
      }
      for (const c of categories || []) {
        const slug = ctByCategory[(c as any).id] || (c as any).slug;
        entries.push({ loc: `${host}/cataleg/${slug}`, lastmod: (c as any).updated_at });
      }

      // Index always references every language sitemap.
      indexItems.push({
        loc: `${SUPABASE_URL}/storage/v1/object/public/${BUCKET}/seo/sitemap-${lang}.xml`,
        lastmod: today,
      });

      if (wantsLang(lang)) {
        uploaded.push({
          path: `seo/sitemap-${lang}.xml`,
          content: buildUrlset(entries),
          type: "application/xml; charset=utf-8",
        });
      }
    }

    const sitemapIndexPublicUrl = `${SUPABASE_URL}/storage/v1/object/public/${BUCKET}/seo/sitemap.xml`;
    if (doIndex) {
      uploaded.push({
        path: "seo/sitemap.xml",
        content: buildSitemapIndex(indexItems),
        type: "application/xml; charset=utf-8",
      });
    }
    if (doRobots) {
      uploaded.push({
        path: "seo/robots.txt",
        content: buildRobots(host, sitemapIndexPublicUrl),
        type: "text/plain; charset=utf-8",
      });
    }


    // Upload all
    for (const f of uploaded) {
      const { error } = await sb.storage.from(BUCKET).upload(f.path, new Blob([f.content], { type: f.type }), {
        upsert: true,
        contentType: f.type,
        cacheControl: "60",
      });
      if (error) {
        return new Response(JSON.stringify({ error: `upload ${f.path}: ${error.message}` }), {
          status: 500,
          headers: { ...cors, "Content-Type": "application/json" },
        });
      }
    }

    const base = `${SUPABASE_URL}/storage/v1/object/public/${BUCKET}/seo`;
    return new Response(
      JSON.stringify({
        ok: true,
        generated_at: new Date().toISOString(),
        robots: `${base}/robots.txt`,
        sitemapIndex: `${base}/sitemap.xml`,
        sitemaps: langs.map((c) => ({ lang: c, url: `${base}/sitemap-${c}.xml` })),
      }),
      { status: 200, headers: { ...cors, "Content-Type": "application/json" } },
    );
  } catch (e) {
    return new Response(JSON.stringify({ error: String(e) }), {
      status: 500,
      headers: { ...cors, "Content-Type": "application/json" },
    });
  }
});
