// Generates public/robots.txt and public/sitemap*.xml at the project root
// so they are served from the hosting root (e.g. https://site.tld/robots.txt
// and /sitemap.xml). Runs via predev/prebuild npm hooks.
//
// Data source: Supabase REST (anon key). Tables read must allow anon SELECT
// for public catalog entries (products, cms pages, categories, brands,
// languages, *_translations). Birth lists are intentionally NEVER included.

import { writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { config as loadEnv } from 'dotenv';

loadEnv();

const SUPABASE_URL = process.env.VITE_SUPABASE_URL || '';
const SUPABASE_KEY = process.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';
const BASE_URL = (process.env.PUBLIC_SITE_URL || 'https://elmussolet.lovable.app').replace(/\/$/, '');

const STATIC_ROUTES: Record<string, string[]> = {
  ca: ['/', '/cataleg', '/contacte', '/llista-naixement', '/politica-cookies'],
  es: ['/', '/cataleg', '/contacto', '/llista-naixement', '/politica-de-cookies'],
};

// Private / non-indexable paths. Shared across locales.
const PRIVATE_PATHS = [
  '/llista-naixement/',
  '/la-meva-llista',
  '/el-meu-compte',
  '/cistella',
  '/checkout',
  '/login',
  '/registre',
  '/recuperar-contrasenya',
  '/reset-password',
  '/admin',
];

function xmlEscape(s: string) {
  return s.replace(/[<>&"']/g, (c) =>
    ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;', "'": '&apos;' }[c]!),
  );
}

async function sb<T = any>(path: string): Promise<T[]> {
  if (!SUPABASE_URL || !SUPABASE_KEY) return [];
  try {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/${path}`, {
      headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}` },
    });
    if (!res.ok) {
      console.warn(`[seo] ${path} -> ${res.status}`);
      return [];
    }
    return (await res.json()) as T[];
  } catch (e) {
    console.warn('[seo] fetch failed', path, e);
    return [];
  }
}

function writeFile(rel: string, body: string) {
  const full = resolve(rel);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, body);
  console.log(`  wrote ${rel} (${body.length} bytes)`);
}

function buildUrlset(entries: { loc: string; lastmod?: string | null }[]) {
  const urls = entries
    .map(
      (e) =>
        `  <url>\n    <loc>${xmlEscape(e.loc)}</loc>${
          e.lastmod ? `\n    <lastmod>${String(e.lastmod).slice(0, 10)}</lastmod>` : ''
        }\n  </url>`,
    )
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`;
}

function buildSitemapIndex(items: { loc: string; lastmod: string }[]) {
  const body = items
    .map(
      (s) =>
        `  <sitemap>\n    <loc>${xmlEscape(s.loc)}</loc>\n    <lastmod>${s.lastmod}</lastmod>\n  </sitemap>`,
    )
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</sitemapindex>\n`;
}

function buildRobots() {
  const ua = (name: string) =>
    [`User-agent: ${name}`, 'Allow: /', ...PRIVATE_PATHS.map((p) => `Disallow: ${p}`)].join('\n');
  return [
    '# El Mussolet — robots.txt',
    '# Generated by scripts/generate-seo.ts',
    `# Host: ${BASE_URL}`,
    '',
    ua('Googlebot'),
    '',
    ua('Bingbot'),
    '',
    ua('Twitterbot'),
    '',
    ua('facebookexternalhit'),
    '',
    ua('*'),
    '',
    `Sitemap: ${BASE_URL}/sitemap.xml`,
    '',
  ].join('\n');
}

async function main() {
  console.log(`[seo] base url: ${BASE_URL}`);

  // Languages
  let languages = await sb<{ code: string; sort_order: number }>(
    'languages?select=code,sort_order,is_enabled&is_enabled=eq.true&order=sort_order.asc',
  );
  if (!languages.length) languages = [{ code: 'ca', sort_order: 0 }, { code: 'es', sort_order: 1 }];
  const langs = languages.map((l) => l.code);

  // Catalog data (once, reused per language)
  const products = await sb<{ id: string; slug: string; updated_at: string }>(
    'products?select=id,slug,updated_at,is_active&is_active=eq.true',
  );
  const productTranslations = await sb<{
    product_id: string;
    language: string;
    slug: string | null;
  }>('product_translations?select=product_id,language,slug');
  const pages = await sb<{ slug: string; updated_at: string }>(
    'cms_blocks?select=slug,updated_at,kind,is_active&kind=eq.page&is_active=eq.true',
  );
  const categories = await sb<{ id: string; slug: string; updated_at: string }>(
    'categories?select=id,slug,updated_at,is_active&is_active=eq.true',
  );
  const categoryTranslations = await sb<{
    category_id: string;
    language: string;
    slug: string | null;
  }>('category_translations?select=category_id,language,slug');
  // Brands intentionally not added: schema has no slug; catalog filters them
  // via name. Skip to keep sitemap clean.

  const today = new Date().toISOString().slice(0, 10);
  const indexItems: { loc: string; lastmod: string }[] = [];

  for (const lang of langs) {
    const entries: { loc: string; lastmod?: string | null }[] = [];

    for (const r of STATIC_ROUTES[lang] || STATIC_ROUTES.ca) {
      entries.push({ loc: `${BASE_URL}${r}` });
    }

    // Products with localized slug fallback
    const ptByProduct: Record<string, string | null> = {};
    for (const t of productTranslations) {
      if (t.language === lang && t.slug) ptByProduct[t.product_id] = t.slug;
    }
    for (const p of products) {
      const slug = ptByProduct[p.id] || p.slug;
      entries.push({ loc: `${BASE_URL}/producte/${slug}`, lastmod: p.updated_at });
    }

    for (const pg of pages) {
      entries.push({ loc: `${BASE_URL}/pagina/${pg.slug}`, lastmod: pg.updated_at });
    }

    const ctByCategory: Record<string, string | null> = {};
    for (const t of categoryTranslations) {
      if (t.language === lang && t.slug) ctByCategory[t.category_id] = t.slug;
    }
    for (const c of categories) {
      const slug = ctByCategory[c.id] || c.slug;
      entries.push({ loc: `${BASE_URL}/cataleg/${slug}`, lastmod: c.updated_at });
    }

    // (brands skipped — see above)

    const file = `public/sitemap-${lang}.xml`;
    writeFile(file, buildUrlset(entries));
    indexItems.push({ loc: `${BASE_URL}/sitemap-${lang}.xml`, lastmod: today });
  }

  writeFile('public/sitemap.xml', buildSitemapIndex(indexItems));
  writeFile('public/robots.txt', buildRobots());

  console.log('[seo] done');
}

main().catch((e) => {
  console.error('[seo] failed', e);
  // Don't break the build — keep going with whatever is currently in public/.
  process.exit(0);
});
