// Dynamic robots.txt generator. No auth required.
// Query params:
//   lang  - optional language (ca, es). If omitted, returns a combined
//           robots that disallows private paths in every locale.
//   host  - base URL used in the Sitemap: directive. Defaults to
//           PUBLIC_SITE_URL or request origin.
// Returns text/plain.

const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, OPTIONS",
};

// Private / non-indexable paths per locale. Birth-list views, cart, checkout,
// account areas, auth flows and admin must never be crawled.
const PRIVATE_PATHS: Record<string, string[]> = {
  ca: [
    "/llista-naixement/",
    "/la-meva-llista",
    "/el-meu-compte",
    "/cistella",
    "/checkout",
    "/login",
    "/registre",
    "/recuperar-contrasenya",
    "/reset-password",
    "/admin",
  ],
  es: [
    "/llista-naixement/",
    "/la-meva-llista",
    "/el-meu-compte",
    "/cistella",
    "/checkout",
    "/login",
    "/registre",
    "/recuperar-contrasenya",
    "/reset-password",
    "/admin",
  ],
};

function blockFor(ua: string, paths: string[]) {
  return [`User-agent: ${ua}`, "Allow: /", ...paths.map((p) => `Disallow: ${p}`)].join("\n");
}

function buildRobots(host: string, langs: string[], sitemapUrl: string, langParam?: string) {
  const ordered = langs.length ? langs : ["ca", "es"];
  // Union of all private paths across requested locales (deduped).
  const targetLangs = langParam ? [langParam] : ordered;
  const all = new Set<string>();
  for (const lng of targetLangs) {
    (PRIVATE_PATHS[lng] || PRIVATE_PATHS.ca).forEach((p) => all.add(p));
  }
  const paths = Array.from(all);

  const blocks = [
    blockFor("Googlebot", paths),
    blockFor("Bingbot", paths),
    blockFor("Twitterbot", paths),
    blockFor("facebookexternalhit", paths),
    blockFor("*", paths),
  ];

  const header = [
    `# El Mussolet — robots.txt`,
    `# Generated by /functions/v1/robots${langParam ? ` (lang=${langParam})` : ""}`,
    `# Host: ${host}`,
  ].join("\n");

  return `${header}\n\n${blocks.join("\n\n")}\n\nSitemap: ${sitemapUrl}\n`;
}

async function fetchLanguages(): Promise<string[]> {
  const SUPABASE_URL = Deno.env.get("SUPABASE_URL");
  const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if (!SUPABASE_URL || !SERVICE_KEY) return ["ca", "es"];
  try {
    const res = await fetch(
      `${SUPABASE_URL}/rest/v1/languages?select=code,sort_order&is_enabled=eq.true&order=sort_order.asc`,
      { headers: { apikey: SERVICE_KEY, Authorization: `Bearer ${SERVICE_KEY}` } },
    );
    if (!res.ok) return ["ca", "es"];
    const rows = (await res.json()) as Array<{ code: string }>;
    const codes = rows.map((r) => r.code).filter(Boolean);
    return codes.length ? codes : ["ca", "es"];
  } catch {
    return ["ca", "es"];
  }
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors });

  try {
    const url = new URL(req.url);
    const langParam = (url.searchParams.get("lang") || "").toLowerCase() || undefined;
    const hostParam = url.searchParams.get("host");
    const host = (hostParam || `${url.protocol}//${url.host}`).replace(/\/$/, "");

    const langs = await fetchLanguages();
    // Sitemap index pointing back to the sitemap function for all enabled locales.
    const sitemapBase = `${url.protocol}//${url.host}/functions/v1/sitemap`;
    const sitemapUrl = `${sitemapBase}?index=1&host=${encodeURIComponent(host)}`;

    const body = buildRobots(host, langs, sitemapUrl, langParam);

    return new Response(body, {
      status: 200,
      headers: {
        ...cors,
        "Content-Type": "text/plain; charset=utf-8",
        "Cache-Control": "public, max-age=600",
        "X-Robots-Tag": "noindex",
      },
    });
  } catch (e) {
    return new Response(`# error: ${String(e)}\nUser-agent: *\nAllow: /\n`, {
      status: 500,
      headers: { ...cors, "Content-Type": "text/plain" },
    });
  }
});
